// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnkdqRLf-ub5e3ZCLvoxjx8B6gb-cPIJc',
    appId: '1:543309871864:web:7b165c1b5f8b56659cd90d',
    messagingSenderId: '543309871864',
    projectId: 'energy-monitoring-app',
    authDomain: 'energy-monitoring-app.firebaseapp.com',
    storageBucket: 'energy-monitoring-app.firebasestorage.app',
    measurementId: 'G-XH2C7M8LRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9caOzEhUiz0rf89zX-rE8PPGv0onVrvg',
    appId: '1:543309871864:android:e93ddf9b6dc10f319cd90d',
    messagingSenderId: '543309871864',
    projectId: 'energy-monitoring-app',
    storageBucket: 'energy-monitoring-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDctIHDJU6wCn5sa8-Z2QjCOus6NNlmCEo',
    appId: '1:543309871864:ios:9c51e7c1eeb7fb9c9cd90d',
    messagingSenderId: '543309871864',
    projectId: 'energy-monitoring-app',
    storageBucket: 'energy-monitoring-app.firebasestorage.app',
    iosBundleId: 'com.example.energyMonitoringApp',
  );

}